fun main(args: Array<String>) {
    println("Queue:")
    var queue: Queue = Queue(5)
    queue.enqueue(10)
    queue.enqueue(5)
    queue.enqueue(56)
    println(queue.dequeue())
    queue.enqueue(11)
    println(queue)
    println("Stack:")
    var stack: Stack = Stack(5)
    stack.push(5)
    stack.push(14)
    stack.push(25)
    println(stack)
    println(stack.pop())
    println(stack)
}
