fun main() {
    println("Queue:")
    var queue = Queue()
    queue.enqueue(10)
    queue.enqueue(5)
    queue.enqueue(56)
    println(queue.dequeue())
    queue.enqueue("11")
    queue.enqueue('8')
    queue.enqueue(57)
    println(queue.dequeue())
    println(queue)
    println("Stack:")
    var stack = Stack()
    stack.push(5)
    stack.push(14)
    stack.push(25)
    println(stack)
    println(stack.pop())
    println(stack.pop())
    println(stack.pop())
    println(stack.pop())
    println(stack.pop())
    stack.push("25")
    println(stack)
}
